// Trust-toolchain slice — the [F5] FRONTEND-MISCOMPILE REGRESSION PIN: the
// production scheduler predicate `call_opcode_clobbers_registers` transcribed
// VERBATIM over the production `AArch64Opcode` enum WITH NO `#[repr]` (exactly
// as production declares it). This is the SAME predicate as in
// trust_opcode_sched_class_slice.rs but WITHOUT the explicit-repr workaround.
//
// HISTORY: under the round-21 [F5] frontend bug, a no-repr fieldless enum's
// tag was read `sext i8`, so every variant >=128 read NEGATIVE, never matched
// an unsigned switch key, and the predicate silently returned its `false`
// default. The frontend has since been FIXED (unsigned tag read); the round-9
// test `trust_f5_norepr_call_clobbers_fixed_bl_blr` pins the FIXED behavior:
// no-repr JIT == native for all four call opcodes.
//
// REGENERATED for the 260-variant enum: with more than 256 variants rustc
// gives the no-repr enum a u16 tag, so this fixture now ALSO pins the u16
// no-repr tag read (Bl=71/Blr=72 below 128; BL=241/BLR=242 above — the
// formerly-F5-prone range).

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AArch64Opcode {
    AddRR,
    AddRI,
    AddRIShift12,
    SubRR,
    SubRI,
    MulRR,
    Msub,
    Smull,
    Umull,
    SDiv,
    UDiv,
    Neg,
    AndRR,
    AndRI,
    OrrRR,
    OrrRI,
    EorRR,
    EorRI,
    OrnRR,
    BicRR,
    LslRR,
    LsrRR,
    AsrRR,
    LslRI,
    LsrRI,
    AsrRI,
    RorRI,
    Rbit,
    CmpRR,
    CmpRI,
    Tst,
    Csel,
    Csinc,
    Csinv,
    Csneg,
    MovR,
    MovI,
    Movz,
    Movn,
    Movk,
    FmovImm,
    LdrRI,
    StrRI,
    LdrPreIndex,
    StrPreIndex,
    LdrPostIndex,
    StrPostIndex,
    LdrbRI,
    LdrhRI,
    LdrsbRI,
    LdrshRI,
    StrbRI,
    StrhRI,
    LdrLiteral,
    LdpRI,
    StpRI,
    StpPreIndex,
    LdpPostIndex,
    LdrRO,
    StrRO,
    LdrbRO,
    LdrhRO,
    LdrGot,
    LdrTlvp,
    B,
    BCond,
    Cbz,
    Cbnz,
    Tbz,
    Tbnz,
    Br,
    Bl,
    Blr,
    Ret,
    CSet,
    Sxtw,
    Uxtw,
    Sxtb,
    Sxth,
    Uxtb,
    Uxth,
    Ubfm,
    Sbfm,
    Bfm,
    FaddRR,
    FsubRR,
    FmulRR,
    FdivRR,
    FmaddRR,
    FminnmRR,
    FmaxnmRR,
    FnegRR,
    FabsRR,
    FsqrtRR,
    FrintmRR,
    FrintpRR,
    FrintzRR,
    Fcmp,
    FcvtzsRR,
    FcvtzuRR,
    ScvtfRR,
    UcvtfRR,
    FcvtSD,
    FcvtDS,
    FcvtHS,
    FcvtHD,
    FcvtSH,
    FcvtDH,
    FmovGprFpr,
    FmovFprGpr,
    FmovFprFpr,
    NeonAddV,
    NeonSubV,
    NeonMulV,
    NeonSmaxV,
    NeonSminV,
    NeonUmaxV,
    NeonUminV,
    NeonFaddV,
    NeonFsubV,
    NeonFmulV,
    NeonFdivV,
    NeonFcmgtV,
    NeonAndV,
    NeonOrrV,
    NeonEorV,
    NeonBicV,
    NeonNotV,
    NeonRbitV,
    NeonRev32V,
    NeonRev64V,
    NeonCmeqV,
    NeonCmgtV,
    NeonCmgeV,
    NeonCmhiV,
    NeonCmhsV,
    NeonUmaxv,
    NeonAddpScalar,
    NeonDupElem,
    NeonDupGen,
    NeonInsGen,
    NeonUmovGen,
    NeonMovi,
    NeonLd1Post,
    NeonLdpQPost,
    NeonSt1Post,
    NeonStpQPost,
    NeonCntV,
    NeonUaddlpV,
    NeonSaddlpV,
    NeonAbsV,
    NeonBitV,
    NeonUdotV,
    NeonExtV,
    NeonFmlaV,
    NeonFmlsV,
    NeonUcvtfV,
    NeonScvtfV,
    NeonDupScalarD,
    Ldar,
    Ldarb,
    Ldarh,
    Stlr,
    Stlrb,
    Stlrh,
    Ldadd,
    Ldadda,
    Ldaddal,
    Ldaddl,
    Ldclr,
    Ldclra,
    Ldclral,
    Ldclrl,
    Ldeor,
    Ldeora,
    Ldeoral,
    Ldeorl,
    Ldset,
    Ldseta,
    Ldsetal,
    Ldsetl,
    Ldsmax,
    Ldsmaxa,
    Ldsmaxal,
    Ldsmaxl,
    Ldsmin,
    Ldsmina,
    Ldsminal,
    Ldsminl,
    Ldumax,
    Ldumaxa,
    Ldumaxal,
    Ldumaxl,
    Ldumin,
    Ldumina,
    Lduminal,
    Lduminl,
    Swp,
    Swpa,
    Swpal,
    Swpl,
    Cas,
    Casa,
    Casal,
    Casl,
    Ldaxr,
    Stlxr,
    Dmb,
    Dsb,
    Isb,
    Adrp,
    Adr,
    AddPCRel,
    LdrswRO,
    AddsRR,
    AddsRI,
    SubsRR,
    SubsRI,
    Adc,
    Sbc,
    Umulh,
    Smulh,
    Madd,
    Brk,
    TrapOverflow,
    TrapBoundsCheck,
    TrapBoundsCheckExact,
    TrapNull,
    TrapNullIfZero,
    TrapDivZero,
    TrapDivZeroIfZero,
    TrapShiftRange,
    TrapShiftRangeIfOOB,
    Retain,
    Release,
    MOVWrr,
    MOVXrr,
    STRWui,
    STRXui,
    STRSui,
    STRDui,
    BL,
    BLR,
    CMPWrr,
    CMPXrr,
    CMPWri,
    CMPXri,
    MOVZWi,
    MOVZXi,
    Bcc,
    Mrs,
    Phi,
    StackAlloc,
    Copy,
    Nop,
    NeonShlVImm,
    NeonUshrVImm,
    NeonSshrVImm,
    TrapOverflowExact,
    TailCall,
}

// ── call_opcode_clobbers_registers (scheduler.rs:1011-1016, VERBATIM) ────────
fn call_opcode_clobbers_registers(opcode: AArch64Opcode) -> bool {
    matches!(
        opcode,
        AArch64Opcode::Bl | AArch64Opcode::Blr | AArch64Opcode::BL | AArch64Opcode::BLR
    )
}

// ── [B1] tag plumbing (total; unknown index -> Nop, a non-call) ──────────────
fn opcode_from_index(idx: u32) -> AArch64Opcode {
    use AArch64Opcode::*;
    match idx {
        0 => AddRR,
        1 => AddRI,
        2 => AddRIShift12,
        3 => SubRR,
        4 => SubRI,
        5 => MulRR,
        6 => Msub,
        7 => Smull,
        8 => Umull,
        9 => SDiv,
        10 => UDiv,
        11 => Neg,
        12 => AndRR,
        13 => AndRI,
        14 => OrrRR,
        15 => OrrRI,
        16 => EorRR,
        17 => EorRI,
        18 => OrnRR,
        19 => BicRR,
        20 => LslRR,
        21 => LsrRR,
        22 => AsrRR,
        23 => LslRI,
        24 => LsrRI,
        25 => AsrRI,
        26 => RorRI,
        27 => Rbit,
        28 => CmpRR,
        29 => CmpRI,
        30 => Tst,
        31 => Csel,
        32 => Csinc,
        33 => Csinv,
        34 => Csneg,
        35 => MovR,
        36 => MovI,
        37 => Movz,
        38 => Movn,
        39 => Movk,
        40 => FmovImm,
        41 => LdrRI,
        42 => StrRI,
        43 => LdrPreIndex,
        44 => StrPreIndex,
        45 => LdrPostIndex,
        46 => StrPostIndex,
        47 => LdrbRI,
        48 => LdrhRI,
        49 => LdrsbRI,
        50 => LdrshRI,
        51 => StrbRI,
        52 => StrhRI,
        53 => LdrLiteral,
        54 => LdpRI,
        55 => StpRI,
        56 => StpPreIndex,
        57 => LdpPostIndex,
        58 => LdrRO,
        59 => StrRO,
        60 => LdrbRO,
        61 => LdrhRO,
        62 => LdrGot,
        63 => LdrTlvp,
        64 => B,
        65 => BCond,
        66 => Cbz,
        67 => Cbnz,
        68 => Tbz,
        69 => Tbnz,
        70 => Br,
        71 => Bl,
        72 => Blr,
        73 => Ret,
        74 => CSet,
        75 => Sxtw,
        76 => Uxtw,
        77 => Sxtb,
        78 => Sxth,
        79 => Uxtb,
        80 => Uxth,
        81 => Ubfm,
        82 => Sbfm,
        83 => Bfm,
        84 => FaddRR,
        85 => FsubRR,
        86 => FmulRR,
        87 => FdivRR,
        88 => FmaddRR,
        89 => FminnmRR,
        90 => FmaxnmRR,
        91 => FnegRR,
        92 => FabsRR,
        93 => FsqrtRR,
        94 => FrintmRR,
        95 => FrintpRR,
        96 => FrintzRR,
        97 => Fcmp,
        98 => FcvtzsRR,
        99 => FcvtzuRR,
        100 => ScvtfRR,
        101 => UcvtfRR,
        102 => FcvtSD,
        103 => FcvtDS,
        104 => FcvtHS,
        105 => FcvtHD,
        106 => FcvtSH,
        107 => FcvtDH,
        108 => FmovGprFpr,
        109 => FmovFprGpr,
        110 => FmovFprFpr,
        111 => NeonAddV,
        112 => NeonSubV,
        113 => NeonMulV,
        114 => NeonSmaxV,
        115 => NeonSminV,
        116 => NeonUmaxV,
        117 => NeonUminV,
        118 => NeonFaddV,
        119 => NeonFsubV,
        120 => NeonFmulV,
        121 => NeonFdivV,
        122 => NeonFcmgtV,
        123 => NeonAndV,
        124 => NeonOrrV,
        125 => NeonEorV,
        126 => NeonBicV,
        127 => NeonNotV,
        128 => NeonRbitV,
        129 => NeonRev32V,
        130 => NeonRev64V,
        131 => NeonCmeqV,
        132 => NeonCmgtV,
        133 => NeonCmgeV,
        134 => NeonCmhiV,
        135 => NeonCmhsV,
        136 => NeonUmaxv,
        137 => NeonAddpScalar,
        138 => NeonDupElem,
        139 => NeonDupGen,
        140 => NeonInsGen,
        141 => NeonUmovGen,
        142 => NeonMovi,
        143 => NeonLd1Post,
        144 => NeonLdpQPost,
        145 => NeonSt1Post,
        146 => NeonStpQPost,
        147 => NeonCntV,
        148 => NeonUaddlpV,
        149 => NeonSaddlpV,
        150 => NeonAbsV,
        151 => NeonBitV,
        152 => NeonUdotV,
        153 => NeonExtV,
        154 => NeonFmlaV,
        155 => NeonFmlsV,
        156 => NeonUcvtfV,
        157 => NeonScvtfV,
        158 => NeonDupScalarD,
        159 => Ldar,
        160 => Ldarb,
        161 => Ldarh,
        162 => Stlr,
        163 => Stlrb,
        164 => Stlrh,
        165 => Ldadd,
        166 => Ldadda,
        167 => Ldaddal,
        168 => Ldaddl,
        169 => Ldclr,
        170 => Ldclra,
        171 => Ldclral,
        172 => Ldclrl,
        173 => Ldeor,
        174 => Ldeora,
        175 => Ldeoral,
        176 => Ldeorl,
        177 => Ldset,
        178 => Ldseta,
        179 => Ldsetal,
        180 => Ldsetl,
        181 => Ldsmax,
        182 => Ldsmaxa,
        183 => Ldsmaxal,
        184 => Ldsmaxl,
        185 => Ldsmin,
        186 => Ldsmina,
        187 => Ldsminal,
        188 => Ldsminl,
        189 => Ldumax,
        190 => Ldumaxa,
        191 => Ldumaxal,
        192 => Ldumaxl,
        193 => Ldumin,
        194 => Ldumina,
        195 => Lduminal,
        196 => Lduminl,
        197 => Swp,
        198 => Swpa,
        199 => Swpal,
        200 => Swpl,
        201 => Cas,
        202 => Casa,
        203 => Casal,
        204 => Casl,
        205 => Ldaxr,
        206 => Stlxr,
        207 => Dmb,
        208 => Dsb,
        209 => Isb,
        210 => Adrp,
        211 => Adr,
        212 => AddPCRel,
        213 => LdrswRO,
        214 => AddsRR,
        215 => AddsRI,
        216 => SubsRR,
        217 => SubsRI,
        218 => Adc,
        219 => Sbc,
        220 => Umulh,
        221 => Smulh,
        222 => Madd,
        223 => Brk,
        224 => TrapOverflow,
        225 => TrapBoundsCheck,
        226 => TrapBoundsCheckExact,
        227 => TrapNull,
        228 => TrapNullIfZero,
        229 => TrapDivZero,
        230 => TrapDivZeroIfZero,
        231 => TrapShiftRange,
        232 => TrapShiftRangeIfOOB,
        233 => Retain,
        234 => Release,
        235 => MOVWrr,
        236 => MOVXrr,
        237 => STRWui,
        238 => STRXui,
        239 => STRSui,
        240 => STRDui,
        241 => BL,
        242 => BLR,
        243 => CMPWrr,
        244 => CMPXrr,
        245 => CMPWri,
        246 => CMPXri,
        247 => MOVZWi,
        248 => MOVZXi,
        249 => Bcc,
        250 => Mrs,
        251 => Phi,
        252 => StackAlloc,
        253 => Copy,
        254 => Nop,
        255 => NeonShlVImm,
        256 => NeonUshrVImm,
        257 => NeonSshrVImm,
        258 => TrapOverflowExact,
        259 => TailCall,
        _ => Nop,
    }
}

#[no_mangle]
pub fn clobbers_root(idx: u32) -> u32 {
    call_opcode_clobbers_registers(opcode_from_index(idx)) as u32
}
