// trust-cg-verify/lrat_cert.rs - ENC-6: machine-checkable LRAT/DRAT proof
// certificates that back trust-cg's Formal (ay UNSAT) verdicts.
//
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Copyright 2026 Andrew Yates | License: Apache-2.0
//
// Reference: docs/beat-llvm-roadmap-2026-07-01.md WORKSTREAM ENCODER, ENC-6;
// docs/enc8-phase1-lrat-throughput-2026-07-02.md (binding: keep large certs on
// the ay bit-blaster + drat-trim TCB — fast C — NOT the clean kernel).

//! **ENC-6 — independent-checker backstop for the ay UNSAT verdicts.**
//!
//! A tier-0 DB row (`crate::verdict_db`) records that `ay` once answered
//! `unsat` for a fixed query. The compile path treats that row only as a
//! candidate and re-runs the solver before crediting it; writable recorded
//! output is not proof authority. ENC-6 provides a machine-checkable offline
//! alternative by attaching a DRAT proof that an **independent** checker
//! (`drat-trim`, Marijn Heule, MIT — vendored as `trust-cg-drat-trim`) verifies.
//!
//! # Why this shrinks the trusted island
//!
//! The 4th trusted island is "ay UNSAT verdicts + statistical >8-bit
//! discharge". For a `QF_BV` obligation, ay does two jobs:
//!
//!  1. **bit-blast** the SMT2 to a DIMACS CNF, and
//!  2. **refute** that exact CNF (a SAT search), emitting a DRAT proof.
//!
//! Both artifacts are transactionally published by one authenticated AY run
//! (`ay solve <smt2> --dump-bv-cnf <cnf> --proof <drat>`); trust-cg never
//! re-solves a detached CNF in a second process.
//!
//! `drat-trim` independently confirms job (2): it replays the DRAT against the
//! CNF and derives the empty clause, i.e. the CNF **is** UNSAT — no trust in
//! ay's SAT engine required. The bit-blast (job 1, SMT2→CNF) stays in the ay
//! TCB; this is exactly the "ay bit-blaster + drat-trim TCB" that ENC-8 names as
//! the intended anchor for the large (v2i64-class) obligations the clean kernel
//! cannot scale to. So ENC-6 does not eliminate the island, it *shrinks* it: the
//! combinatorially-hard half of every certified verdict becomes independently
//! re-checkable.
//!
//! # Schema binding
//!
//! A cert carries the SAME `verdict_key` a tier-0 row uses
//! ([`crate::ay_bridge::verdict_cache_key_v2`] over the solver identity and the
//! byte-identical `crate::verdict_db::db_obligation_smt2` query), so a cert
//! provably backs a *specific* verdict-DB row and can never be silently
//! re-pointed at a different obligation.
//!
//! # Scope / cost
//!
//! This is an **opt-in / offline** lane. Nothing here runs on the per-compile
//! hot path; candidate rows are currently revalidated with live ay instead of
//! consuming these certificates. Certificate *generation* shells out to `ay`;
//! certificate *re-checking* shells out to `drat-trim`. Both executables are
//! passed in as paths, so the library carries **no** production dependency on
//! either — tests supply the vendored `drat-trim` (dev-dependency) and the
//! resolved `ay` binary.
//!
//! # Teeth
//!
//! A cert that "verifies" the wrong obligation is worse than nothing.
//! [`recheck_cert`] therefore (a) re-derives the recorded CNF's SHA-256 and
//! refuses a cert whose CNF bytes were altered, and (b) requires `drat-trim` to
//! print `s VERIFIED` at a success exit — a tampered proof yields `s NOT
//! VERIFIED` at a non-zero exit and is rejected. Both are covered by the module
//! tests.

use std::path::Path;
use std::process::Command;

use sha2::{Digest, Sha256};

/// Schema line every serialized cert file starts with.
pub const LRAT_CERT_SCHEMA_LINE: &str = "tcg-lrat-cert-v3";

/// The predecessor schema, still ACCEPTED on read.
///
/// v2 certs carry no `smt2` section, so they cannot be checked against the
/// obligation they name — [`LratCert::carries_obligation_binding`] reports
/// false for them and [`recheck_cert`] skips that check rather than pretending
/// to perform it. They are otherwise re-checked exactly as before, so accepting
/// them is status quo, not a weakening.
///
/// Both versions are accepted because the committed canary certificates are
/// `include_str!`-embedded and can only be regenerated by a machine with a
/// working `ay` (`cargo run --release -p trust-cg-verify --bin
/// regen_canary_certs`). Minting v3 while still reading v2 lets the binding
/// arrive without stranding the repo on an environment it cannot reproduce.
pub const LRAT_CERT_SCHEMA_LINE_V2: &str = "tcg-lrat-cert-v2";

/// Exit code a DIMACS-mode SAT solve returns for UNSATISFIABLE (the SAT
/// competition convention; 10 is SATISFIABLE). A DIMACS run therefore reports
/// success-as-refutation via a NON-zero status, so `ExitStatus::success()` must
/// not be used to gate it.
const DIMACS_UNSAT_EXIT: i32 = 20;

/// Lowercase-hex SHA-256 of `bytes`, matching the digest spelling used by
/// [`crate::ay_bridge::verdict_cache_key_v2`] and `solver_identity_hash`.
pub fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

/// The outcome of an independent `drat-trim` re-check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DratTrimOutcome {
    /// `drat-trim` replayed the proof against the CNF and derived the empty
    /// clause: the formula is independently confirmed UNSAT.
    Verified,
    /// `drat-trim` ran but did NOT confirm UNSAT (tampered / insufficient
    /// proof, or a satisfiable formula). Carries the checker's reason line(s).
    NotVerified(String),
    /// The check could not be performed (missing binary, I/O failure, CNF
    /// integrity mismatch). NOT a verdict — the caller must not credit it.
    Error(String),
}

impl DratTrimOutcome {
    /// True only for [`DratTrimOutcome::Verified`]. Use this to gate crediting:
    /// `NotVerified` and `Error` are both non-credits.
    pub fn is_verified(&self) -> bool {
        matches!(self, DratTrimOutcome::Verified)
    }
}

/// A machine-checkable certificate that a specific Formal verdict's `QF_BV`
/// obligation is UNSAT.
///
/// Self-contained: it records the exact bit-blasted CNF and the DRAT proof, so
/// [`recheck_cert`] re-runs `drat-trim` with no other inputs. The `verdict_key`
/// ties it to a `verdict_db` tier-0 row; `cnf_sha256` binds the recorded CNF to
/// the proof so neither can be swapped without detection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LratCert {
    /// The v2 verdict key of the row this cert backs
    /// (`verdict_cache_key_v2(solver_identity, obligation_smt2)`).
    pub verdict_key: String,
    /// Lowercase-hex SHA-256 of the `ay` solver binary that produced the proof.
    pub solver_identity: String,
    /// Diagnostic obligation name (informational).
    pub obligation_name: String,
    /// Lowercase-hex SHA-256 of `cnf` (integrity binding CNF↔proof).
    pub cnf_sha256: String,
    /// The bit-blasted DIMACS CNF from AY's transactional proof run.
    pub cnf: String,
    /// The DRAT proof published for `cnf` by that same AY run.
    pub drat: String,
    /// The SMT2 obligation text this cert certifies (schema v3).
    ///
    /// # Why the TEXT and not a hash
    ///
    /// A `smt2_sha256` field would be redundant: `verdict_key` is already
    /// `SHA256("tcg-proof-cache-v2\0" || solver_identity || "\0" || smt2)`
    /// (`ay_bridge::verdict_cache_key_v2`), and the consume path derives that key
    /// in-process from the LIVE obligation, so a key hit already implies
    /// byte-identical SMT2. Storing a second digest of the same bytes proves
    /// nothing new.
    ///
    /// Storing the TEXT is what actually shrinks the trusted link. The two-run
    /// split (SMT2 -> CNF, then CNF -> DRAT) means `drat-trim` no longer
    /// incidentally cross-checks that the recorded CNF really is this
    /// obligation's bit-blasting — the DRAT is derived from whatever bytes sit at
    /// `cnf_path`. With the SMT2 in the artifact an OFFLINE auditor can re-run
    /// the bit-blast and diff it against the recorded CNF, which is the only
    /// thing that closes that correspondence gap without trusting AY's export
    /// transaction. AY's exporter writes no digest of the query at all.
    pub smt2: String,
}

impl LratCert {
    /// Whether this cert carries the schema-v3 obligation binding (its own SMT2
    /// text), so `recheck_cert` can re-derive `verdict_key` from it.
    ///
    /// False for legacy v2 artifacts. A caller that requires the correspondence
    /// property — "this CNF is THIS obligation's bit-blasting", the half
    /// `drat-trim` stopped covering when generation split into two AY runs —
    /// must gate on this rather than assume every cert provides it.
    pub fn carries_obligation_binding(&self) -> bool {
        !self.smt2.is_empty()
    }

    /// Construct a cert, computing `cnf_sha256` from `cnf`.
    pub fn new(
        verdict_key: impl Into<String>,
        solver_identity: impl Into<String>,
        obligation_name: impl Into<String>,
        cnf: impl Into<String>,
        drat: impl Into<String>,
        smt2: impl Into<String>,
    ) -> Self {
        let cnf = cnf.into();
        let cnf_sha256 = sha256_hex(cnf.as_bytes());
        LratCert {
            verdict_key: verdict_key.into(),
            solver_identity: solver_identity.into(),
            obligation_name: obligation_name.into(),
            cnf_sha256,
            cnf,
            drat: drat.into(),
            smt2: smt2.into(),
        }
    }
}

// ---------------------------------------------------------------------------
// Independent re-check (the teeth)
// ---------------------------------------------------------------------------

/// Interpret a `drat-trim` run. `drat-trim` prints `s VERIFIED` on a confirmed
/// UNSAT and `s NOT VERIFIED` otherwise; on a good proof it exits 0, on a bad
/// one it exits non-zero. We require BOTH signals to agree on success and treat
/// any disagreement conservatively as a non-credit, so a future upstream that
/// changed one signal alone can never be mistaken for a pass.
fn interpret_drat_trim(output: &std::process::Output) -> DratTrimOutcome {
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let says_not_verified = stdout.contains("NOT VERIFIED") || stderr.contains("NOT VERIFIED");
    let says_verified =
        !says_not_verified && (stdout.contains("s VERIFIED") || stdout.contains("\nVERIFIED"));
    if output.status.success() && says_verified {
        DratTrimOutcome::Verified
    } else if says_not_verified || !output.status.success() {
        // A concrete rejection (bad/insufficient proof or SAT formula).
        let reason: String = stdout
            .lines()
            .filter(|l| {
                l.contains("NOT VERIFIED")
                    || l.contains("ERROR")
                    || l.contains("conflict")
                    || l.starts_with("s ")
            })
            .collect::<Vec<_>>()
            .join("; ");
        DratTrimOutcome::NotVerified(if reason.is_empty() {
            format!("drat-trim exit {:?}", output.status.code())
        } else {
            reason
        })
    } else {
        // Ran, exit 0, but no VERIFIED banner: ambiguous → non-credit.
        DratTrimOutcome::Error(format!(
            "drat-trim produced no VERIFIED banner (exit {:?})",
            output.status.code()
        ))
    }
}

/// Run the vendored `drat-trim` at `drat_trim_exe` on `cnf_path` + `proof_path`
/// and interpret the result. This is the INDEPENDENT half of ENC-6: no ay code
/// participates, so a `Verified` here is a check ay did not perform.
pub fn drat_trim_check(
    drat_trim_exe: &Path,
    cnf_path: &Path,
    proof_path: &Path,
) -> DratTrimOutcome {
    let output = match Command::new(drat_trim_exe)
        .arg(cnf_path)
        .arg(proof_path)
        .output()
    {
        Ok(o) => o,
        Err(e) => {
            return DratTrimOutcome::Error(format!(
                "spawning drat-trim ({}) failed: {e}",
                drat_trim_exe.display()
            ));
        }
    };
    interpret_drat_trim(&output)
}

/// Re-check a recorded cert with an independent `drat-trim`. Rejects (with
/// [`DratTrimOutcome::Error`]) BEFORE spawning the checker if the recorded CNF
/// bytes no longer hash to `cnf_sha256` — a tampered CNF can never reach the
/// checker paired with a proof that was made for the original CNF.
///
/// `workdir` is where the CNF/proof are materialized for the subprocess; use a
/// fresh temp dir per call.
pub fn recheck_cert(cert: &LratCert, drat_trim_exe: &Path, workdir: &Path) -> DratTrimOutcome {
    let actual = sha256_hex(cert.cnf.as_bytes());
    if actual != cert.cnf_sha256 {
        return DratTrimOutcome::Error(format!(
            "cnf integrity mismatch: recorded cnf_sha256={} but recorded CNF hashes to {actual}",
            cert.cnf_sha256
        ));
    }
    // OBLIGATION BINDING (schema v3). Re-derive the verdict key from the
    // RECORDED SMT2 and solver identity and require it to reproduce the recorded
    // key. Without this a cert is only self-consistent: it says "this DRAT
    // refutes this CNF" and names a verdict key, with nothing tying that key to
    // the obligation text in the same artifact. An auditor could not tell a cert
    // for obligation A carrying B's key from a genuine one.
    //
    // This is cheap (one SHA-256, no solver) and it is the half `drat-trim`
    // stopped covering when the generation path split into two AY runs — the
    // DRAT is derived from whatever bytes sit at `cnf_path`, so drat-trim
    // verifies job 2 (this CNF is UNSAT) but no longer incidentally guards job 1
    // (this CNF is THIS obligation's bit-blasting).
    // A v2 (legacy) cert carries no obligation text, so this check is not
    // performable. It is SKIPPED, never faked — `carries_obligation_binding()`
    // reports the difference so a caller can require the stronger property.
    let expected_key = crate::ay_bridge::verdict_cache_key_v2(&cert.solver_identity, &cert.smt2);
    if cert.carries_obligation_binding() && expected_key != cert.verdict_key {
        return DratTrimOutcome::Error(format!(
            "obligation binding mismatch: recorded verdict_key={} but (solver_identity, smt2) \
             derives {expected_key} — this cert does not certify the obligation it records",
            cert.verdict_key
        ));
    }
    if let Err(e) = std::fs::create_dir_all(workdir) {
        return DratTrimOutcome::Error(format!("cannot create workdir {}: {e}", workdir.display()));
    }
    let cnf_path = workdir.join("cert.cnf");
    let proof_path = workdir.join("cert.drat");
    if let Err(e) = std::fs::write(&cnf_path, cert.cnf.as_bytes()) {
        return DratTrimOutcome::Error(format!("cannot write {}: {e}", cnf_path.display()));
    }
    if let Err(e) = std::fs::write(&proof_path, cert.drat.as_bytes()) {
        return DratTrimOutcome::Error(format!("cannot write {}: {e}", proof_path.display()));
    }
    drat_trim_check(drat_trim_exe, &cnf_path, &proof_path)
}

// ---------------------------------------------------------------------------
// Serialization (recording a cert as a committable artifact)
// ---------------------------------------------------------------------------

/// Serialize a cert to the strict `tcg-lrat-cert-v2` text format. The CNF and
/// DRAT payloads are length-framed (they are multi-line), mirroring the
/// `verdict_db` row framing. Round-trips through [`parse_cert`] before
/// returning, so a renderer bug can never emit a cert the parser would misread.
pub fn render_cert(cert: &LratCert) -> Result<String, String> {
    for (label, v) in [
        ("verdict_key", &cert.verdict_key),
        ("solver_identity", &cert.solver_identity),
        ("cnf_sha256", &cert.cnf_sha256),
    ] {
        if v.len() != 64
            || !v
                .bytes()
                .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        {
            return Err(format!("{label} must be 64 lowercase hex chars, got {v:?}"));
        }
    }
    if cert.obligation_name.is_empty() || cert.obligation_name.contains('\n') {
        return Err(format!(
            "invalid obligation name {:?}",
            cert.obligation_name
        ));
    }
    if sha256_hex(cert.cnf.as_bytes()) != cert.cnf_sha256 {
        return Err("cnf_sha256 does not match cnf bytes".to_string());
    }

    let mut out = String::new();
    out.push_str(LRAT_CERT_SCHEMA_LINE);
    out.push('\n');
    out.push_str(&format!("verdict-sha256: {}\n", cert.verdict_key));
    out.push_str(&format!("solver-sha256: {}\n", cert.solver_identity));
    out.push_str(&format!("cnf-sha256: {}\n", cert.cnf_sha256));
    out.push_str(&format!("obligation: {}\n", cert.obligation_name));
    out.push_str(&format!("cnf {}\n", cert.cnf.len()));
    out.push_str(&cert.cnf);
    out.push('\n');
    out.push_str(&format!("drat {}\n", cert.drat.len()));
    out.push_str(&cert.drat);
    out.push('\n');
    out.push_str(&format!("smt2 {}\n", cert.smt2.len()));
    out.push_str(&cert.smt2);
    out.push('\n');

    match parse_cert(&out) {
        Ok(parsed) if &parsed == cert => Ok(out),
        Ok(_) => Err("render/parse round-trip mismatch".to_string()),
        Err(e) => Err(format!("rendered cert fails to parse: {e}")),
    }
}

/// Parse a `tcg-lrat-cert-v2` cert. STRICT: any malformed construct is an error
/// (a corrupt cert is never silently half-read). Re-derives and enforces
/// `cnf_sha256` from the recorded CNF bytes, so a cert whose header hash was
/// edited to disagree with its payload is rejected at parse time.
pub fn parse_cert(text: &str) -> Result<LratCert, String> {
    let bytes = text.as_bytes();
    let mut pos = 0usize;

    let next_line = |pos: &mut usize| -> Result<String, String> {
        if *pos >= bytes.len() {
            return Err("unexpected end of cert".to_string());
        }
        let start = *pos;
        let end = bytes[start..]
            .iter()
            .position(|&b| b == b'\n')
            .map(|i| start + i)
            .ok_or_else(|| "missing trailing newline".to_string())?;
        *pos = end + 1;
        String::from_utf8(bytes[start..end].to_vec()).map_err(|_| "non-UTF8 line".to_string())
    };
    let framed = |pos: &mut usize, tag: &str| -> Result<String, String> {
        let header = next_line(pos)?;
        let len_str = header
            .strip_prefix(&format!("{tag} "))
            .ok_or_else(|| format!("expected '{tag} <len>' line, got {header:?}"))?;
        let len: usize = len_str
            .parse()
            .map_err(|_| format!("malformed {tag} length in {header:?}"))?;
        let end = pos
            .checked_add(len)
            .filter(|&e| e <= bytes.len())
            .ok_or_else(|| format!("{tag} payload overruns the cert"))?;
        let payload = String::from_utf8(bytes[*pos..end].to_vec())
            .map_err(|_| format!("{tag} payload is not UTF-8"))?;
        *pos = end;
        if *pos >= bytes.len() || bytes[*pos] != b'\n' {
            return Err(format!("{tag} payload missing its newline separator"));
        }
        *pos += 1;
        Ok(payload)
    };
    let hex_field = |line: &str, prefix: &str| -> Result<String, String> {
        let v = line
            .strip_prefix(prefix)
            .ok_or_else(|| format!("expected {prefix:?} line, got {line:?}"))?;
        if v.len() != 64
            || !v
                .bytes()
                .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        {
            return Err(format!(
                "{prefix} value must be 64 lowercase hex chars, got {v:?}"
            ));
        }
        Ok(v.to_string())
    };

    let schema = next_line(&mut pos)?;
    // v3 carries the obligation text; v2 does not. Both are accepted on READ
    // (see LRAT_CERT_SCHEMA_LINE_V2); v3 is what render_cert MINTS.
    let is_v3 = schema == LRAT_CERT_SCHEMA_LINE;
    if !is_v3 && schema != LRAT_CERT_SCHEMA_LINE_V2 {
        return Err(format!(
            "unrecognized schema line {schema:?} (expected {LRAT_CERT_SCHEMA_LINE:?}              or {LRAT_CERT_SCHEMA_LINE_V2:?})"
        ));
    }
    let verdict_key = hex_field(&next_line(&mut pos)?, "verdict-sha256: ")?;
    let solver_identity = hex_field(&next_line(&mut pos)?, "solver-sha256: ")?;
    let cnf_sha256 = hex_field(&next_line(&mut pos)?, "cnf-sha256: ")?;
    let name_line = next_line(&mut pos)?;
    let obligation_name = name_line
        .strip_prefix("obligation: ")
        .ok_or_else(|| format!("expected 'obligation: <name>' line, got {name_line:?}"))?
        .to_string();
    if obligation_name.is_empty() {
        return Err("empty obligation name".to_string());
    }
    let cnf = framed(&mut pos, "cnf")?;
    let drat = framed(&mut pos, "drat")?;
    // v2 has no `smt2` section; it parses to the empty string, which
    // `carries_obligation_binding()` reports as "binding not carried".
    let smt2 = if is_v3 {
        framed(&mut pos, "smt2")?
    } else {
        String::new()
    };
    if pos != bytes.len() {
        return Err("trailing bytes after cert".to_string());
    }
    // Enforce the integrity binding at parse time: header hash MUST match the
    // recorded CNF. A cert claiming a hash it cannot reproduce is rejected.
    let actual = sha256_hex(cnf.as_bytes());
    if actual != cnf_sha256 {
        return Err(format!(
            "cnf-sha256 header {cnf_sha256} disagrees with recorded CNF (hashes to {actual})"
        ));
    }
    Ok(LratCert {
        verdict_key,
        solver_identity,
        obligation_name,
        cnf_sha256,
        cnf,
        drat,
        smt2,
    })
}

// ---------------------------------------------------------------------------
// Offline generation (the ay half — opt-in, never on the compile path)
// ---------------------------------------------------------------------------

/// Generate an LRAT/DRAT certificate for a `QF_BV` obligation SMT2 query,
/// end-to-end:
///
///  1a. `ay solve <smt2> --dump-bv-cnf <cnf>` — bit-blast and dump the CNF
///      (SMT-LIB mode; AY refuses a non-Alethe `--proof` here).
///  1b. `ay solve <cnf> --proof <drat> --no-verify-proof` — refute the dumped
///      CNF in DIMACS mode and emit the DRAT (UNSAT is exit 20).
///  2.  `drat-trim <cnf> <drat>` — INDEPENDENTLY confirm, else fail.
///
/// The cert's `verdict_key` is computed as
/// `verdict_cache_key_v2(solver_identity, smt2)` so it backs the byte-identical
/// verdict-DB row. Returns `Err` (never a bogus cert) if ay does not answer
/// `unsat`, if the obligation is not bit-blastable to a pure CNF (e.g. array
/// theories), or if `drat-trim` does not independently confirm.
/// What AY's `--dump-bv-cnf` exporter actually wrote, as stated by the artifact's
/// own in-band header. See [`classify_dumped_cnf`].
#[derive(Debug, Clone, PartialEq, Eq)]
enum DumpedCnf {
    /// A genuine eager bit-blast of the query, carrying `clauses` clauses.
    BitBlasted { clauses: u64 },
    /// AY's SMT rewriter closed the query before the bit-blaster ran, so the
    /// export is the canonical false formula (`p cnf 0 1` / `0`) rather than a
    /// blast of the obligation.
    SimplifierClosed,
    /// The canonical TRUE formula — satisfiable, so not a refutation at all.
    CanonicalTrue,
    /// No `c ay export pid <PID> ...` line matching the process we spawned:
    /// a stale, foreign, or truncated artifact.
    ForeignProvenance { found: String },
}

/// Classify AY's `--dump-bv-cnf` artifact from its in-band header, requiring the
/// export to have been produced by process `expected_pid`.
///
/// The exporter emits, in order:
///
/// ```text
/// c ay export pid <PID> generation <N>
/// c ay bit-blasted QF_BV CNF (--dump-bv-cnf)     <- or `canonical false` / `canonical true`
/// c complete eager encoding of the current check-sat query
/// p cnf <vars> <clauses>
/// ```
///
/// The PID line is checked FIRST: without it nothing else about the file can be
/// attributed to this run.
fn classify_dumped_cnf(cnf_text: &str, expected_pid: u32) -> DumpedCnf {
    const PID_PREFIX: &str = "c ay export pid ";
    const BIT_BLASTED: &str = "c ay bit-blasted QF_BV CNF";
    const CANONICAL_FALSE: &str = "c ay canonical false CNF";
    const CANONICAL_TRUE: &str = "c ay canonical true CNF";

    let provenance = cnf_text
        .lines()
        .map(str::trim)
        .find(|l| l.starts_with(PID_PREFIX));
    let Some(provenance) = provenance else {
        return DumpedCnf::ForeignProvenance {
            found: "no `c ay export pid` line".to_string(),
        };
    };
    // `c ay export pid <PID> generation <N>` — take the PID field only; the
    // generation counter is AY-internal and may advance between builds.
    let pid_ok = provenance
        .strip_prefix(PID_PREFIX)
        .and_then(|rest| rest.split_whitespace().next())
        .and_then(|pid| pid.parse::<u32>().ok())
        .is_some_and(|pid| pid == expected_pid);
    if !pid_ok {
        return DumpedCnf::ForeignProvenance {
            found: provenance.to_string(),
        };
    }
    if cnf_text
        .lines()
        .any(|l| l.trim().starts_with(CANONICAL_FALSE))
    {
        return DumpedCnf::SimplifierClosed;
    }
    if cnf_text
        .lines()
        .any(|l| l.trim().starts_with(CANONICAL_TRUE))
    {
        return DumpedCnf::CanonicalTrue;
    }
    if !cnf_text.lines().any(|l| l.trim().starts_with(BIT_BLASTED)) {
        return DumpedCnf::ForeignProvenance {
            found: "export carries this run's pid but no recognized body marker".to_string(),
        };
    }
    // `p cnf <vars> <clauses>` — the clause count the DRAT step will consume.
    let clauses = cnf_text
        .lines()
        .map(str::trim)
        .find_map(|l| {
            let rest = l.strip_prefix("p cnf ")?;
            rest.split_whitespace().nth(1)?.parse::<u64>().ok()
        })
        .unwrap_or(0);
    DumpedCnf::BitBlasted { clauses }
}

pub fn generate_cert_for_smt2(
    obligation_name: &str,
    smt2: &str,
    ay_exe: &Path,
    drat_trim_exe: &Path,
    workdir: &Path,
) -> Result<LratCert, String> {
    let solver_identity = crate::ay_bridge::solver_identity_hash(&ay_exe.to_string_lossy())
        .ok_or_else(|| format!("cannot read/hash ay binary at {}", ay_exe.display()))?;

    std::fs::create_dir_all(workdir)
        .map_err(|e| format!("cannot create workdir {}: {e}", workdir.display()))?;
    let smt2_path = workdir.join("obligation.smt2");
    let cnf_path = workdir.join("obligation.cnf");
    let drat_path = workdir.join("obligation.drat");
    // Clear any artifacts left in this workdir before producing our own. Both
    // the CNF and the DRAT are admitted downstream on an `is_file()` check, so a
    // leftover from an earlier obligation could otherwise be mistaken for this
    // run's output and bound into the cert — a stale CNF would survive exactly
    // the simplifier-closed path that is supposed to REFUSE to mint. Fail
    // closed if a stale artifact cannot be removed, rather than racing it.
    for stale in [&cnf_path, &drat_path] {
        match std::fs::remove_file(stale) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(format!(
                    "cannot clear stale artifact {}: {e}",
                    stale.display()
                ));
            }
        }
    }
    std::fs::write(&smt2_path, smt2.as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", smt2_path.display()))?;

    // 1. Bit-blast the obligation and dump the CNF (SMT-LIB mode).
    //
    // This used to be a SINGLE run that also emitted the DRAT, on the rationale
    // that AY authenticates transactional proof publication to the active solve.
    // AY no longer supports that form: `adapt_proof_config_for_smt`
    // (ay/crates/ay/src/run.rs:57) passes an EXPLICIT `--proof` through
    // unchanged, and SMT-LIB mode then hard-exits on any non-Alethe format
    // ("SMT-LIB mode requires Alethe output", run.rs:2665/2942) — deliberately,
    // per that function's own doc. `--quiet` was likewise removed from
    // `ay solve` (it survives only on the separate `ay-bench` binary).
    //
    // So the DRAT is now produced by a second, DIMACS-mode run over the dumped
    // CNF (step 1b).
    //
    // BE HONEST ABOUT WHAT THAT COSTS. Under the single-run design the DRAT was
    // EXTRINSIC evidence: it was emitted while refuting the formula AY had
    // actually blasted, so `drat-trim(dumped_cnf, drat) == VERIFIED` doubled as
    // a cross-check that the dumped CNF really was that formula — a substituted
    // or truncated CNF would not admit that DRAT. Under the two-run design the
    // DRAT is DERIVED FROM whatever bytes sit at `cnf_path`, so VERIFIED is
    // obtainable for ANY unsatisfiable file there and drat-trim carries no
    // information about the obligation. drat-trim still does its stated job
    // (job 2: this CNF is UNSAT, no trust in AY's SAT engine), but it no longer
    // incidentally guards job 1 (SMT2 -> CNF).
    //
    // That guard is therefore re-established explicitly below, by requiring AY's
    // own IN-BAND export provenance header for THIS run and THIS path, and by
    // clearing stale artifacts up front. A cert-carried `smt2_sha256` would bind
    // it in the artifact itself; that is a schema change (tcg-lrat-cert-v2 -> v3)
    // and is tracked separately.
    // `--no-verify-proof` keeps AY from VERIFYING the default Alethe proof it
    // synthesizes, which trust-cg never consumes. (It does not suppress the
    // stray `<smt2>.alethe` artifact itself — only `--no-proof` does that — so
    // callers may still see one in their workdir.) drat-trim below is the
    // independent check.
    //
    // SPAWNED, not `output()`, because the provenance check below binds the
    // artifact to THIS child's PID, which requires the handle before the wait.
    let solve_child = Command::new(ay_exe)
        .arg("solve")
        .arg(&smt2_path)
        .arg("--dump-bv-cnf")
        .arg(&cnf_path)
        .arg("--no-verify-proof")
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("spawning ay CNF generation failed: {e}"))?;
    let solver_pid = solve_child.id();
    let solve = solve_child
        .wait_with_output()
        .map_err(|e| format!("waiting for ay CNF generation failed: {e}"))?;
    let solve_out = String::from_utf8_lossy(&solve.stdout);
    let solve_err = String::from_utf8_lossy(&solve.stderr);
    // Canonical verdict-DB queries are verdict-only.  A nonzero status or any
    // SMT-LIB error is therefore a hard protocol/solver failure; there is no
    // model-after-UNSAT exception to accept.
    if !solve.status.success()
        || solve_out
            .lines()
            .any(|line| line.trim().starts_with("(error"))
    {
        return Err(format!(
            "ay CNF generation failed for {obligation_name:?} with status {} (stdout: \
             {}; stderr: {})",
            solve.status,
            solve_out.trim(),
            solve_err.trim()
        ));
    }
    if solve_out.lines().any(|l| l.trim() == "sat") {
        return Err(format!(
            "ay reports SAT for obligation {obligation_name:?} — NOT a Formal (unsat) verdict; \
             refusing to mint a cert"
        ));
    }
    if !solve_out.lines().any(|l| l.trim() == "unsat") {
        return Err(format!(
            "ay did not report unsat for {obligation_name:?} (stdout: {})",
            solve_out.trim()
        ));
    }
    // PROVENANCE. `cnf_path.is_file()` would only prove that *a* file exists —
    // an inference, not a fact about this run, and one a leftover from an
    // earlier obligation satisfies. Require instead a POSITIVE statement, from
    // the artifact itself, that THIS process wrote it by genuinely bit-blasting.
    //
    // AY's `--dump-bv-cnf` exporter states that IN-BAND, in the first two lines:
    //
    //     c ay export pid <PID> generation <N>
    //     c ay bit-blasted QF_BV CNF (--dump-bv-cnf)
    //
    // and marks the two degenerate outcomes with distinct body markers instead:
    // `c ay canonical false CNF` (the SMT rewriter closed the query before the
    // bit-blaster ran) and `c ay canonical true CNF`.
    //
    // Checking the header rather than the stderr transcript is deliberate and is
    // STRICTLY STRONGER than the transcript line this replaces: the evidence
    // travels inside the very bytes step 1b consumes, and the PID ties them to
    // the child we just spawned, so a leftover artifact from an earlier
    // obligation (or a concurrent run) cannot satisfy it. It also fixes a real
    // FALSE NEGATIVE: the previous check scraped for a `[dump_cnf] Wrote ...`
    // line that the current AY does not emit at all (it survives only in the
    // legacy standalone dumper), so EVERY obligation was refused and the
    // diagnostic misattributed a solver-transcript drift to the obligation.
    //
    // Refusing the `canonical false` case is the point, not a limitation: AY
    // writes `p cnf 0 1` / `0` for it, which drat-trim happily reports as
    // `c trivial UNSAT` / `s VERIFIED`. Minting a cert from that would carry
    // ZERO information about the obligation. Same for an empty/absent formula.
    //
    // This matters more than it used to. See the step-1b comment: drat-trim no
    // longer cross-checks the CNF against the obligation, so "this CNF is the
    // one AY just blasted from this SMT2" has to be asserted here or nowhere.
    let cnf_text = std::fs::read_to_string(&cnf_path).map_err(|e| {
        format!(
            "no DRAT certificate available for {obligation_name:?}: ay wrote no readable CNF \
             at {} ({e}) — refusing to certify a formula this run did not produce",
            cnf_path.display()
        )
    })?;
    match classify_dumped_cnf(&cnf_text, solver_pid) {
        DumpedCnf::BitBlasted { clauses } if clauses > 0 => {}
        DumpedCnf::BitBlasted { .. } => {
            return Err(format!(
                "no DRAT certificate available for {obligation_name:?}: ay's export at {} is \
                 bit-blasted but EMPTY (0 clauses); refuting the empty formula is trivially \
                 satisfiable, so there is nothing to certify",
                cnf_path.display()
            ));
        }
        DumpedCnf::SimplifierClosed => {
            return Err(format!(
                "no DRAT certificate available for {obligation_name:?}: ay's SMT rewriter closed \
                 the query before the bit-blaster ran (canonical-false export at {}) — a DRAT \
                 over that canonical formula would carry no information about the obligation",
                cnf_path.display()
            ));
        }
        DumpedCnf::CanonicalTrue => {
            return Err(format!(
                "no DRAT certificate available for {obligation_name:?}: ay exported a \
                 canonical-TRUE CNF at {} — that is a satisfiable formula, not a refutation",
                cnf_path.display()
            ));
        }
        DumpedCnf::ForeignProvenance { found } => {
            return Err(format!(
                "refusing to certify {obligation_name:?}: the CNF at {} does not carry THIS \
                 run's export provenance (expected `c ay export pid {solver_pid} ...`, found \
                 {found:?}) — it is a stale or foreign artifact, not the formula this run blasted",
                cnf_path.display()
            ));
        }
    }
    // 1b. DIMACS mode over the dumped CNF: emit the DRAT refutation.
    // A DIMACS solve reports UNSAT as exit code 20 with `s UNSATISFIABLE` on
    // stdout (exit 10 / `s SATISFIABLE` is the SAT answer), so `success()` is
    // NOT the right predicate here.
    let proof = Command::new(ay_exe)
        .arg("solve")
        .arg(&cnf_path)
        .arg("--proof")
        .arg(&drat_path)
        .arg("--no-verify-proof")
        .output()
        .map_err(|e| format!("spawning ay DRAT generation failed: {e}"))?;
    let proof_out = String::from_utf8_lossy(&proof.stdout);
    let proof_err = String::from_utf8_lossy(&proof.stderr);
    if proof_out.lines().any(|l| l.trim() == "s SATISFIABLE") {
        return Err(format!(
            "ay reports SAT for the dumped CNF of {obligation_name:?} — the bit-blasted formula \
             disagrees with the SMT-LIB unsat verdict; refusing to mint a cert"
        ));
    }
    if proof.status.code() != Some(DIMACS_UNSAT_EXIT)
        || !proof_out.lines().any(|l| l.trim() == "s UNSATISFIABLE")
    {
        return Err(format!(
            "ay DRAT generation over the dumped CNF failed for {obligation_name:?} with status \
             {} (expected exit {DIMACS_UNSAT_EXIT} and `s UNSATISFIABLE`) (stdout: {}; stderr: {})",
            proof.status,
            proof_out.trim(),
            proof_err.trim()
        ));
    }
    if !drat_path.is_file() {
        return Err(format!(
            "ay did not emit a DRAT proof at {}",
            drat_path.display()
        ));
    }
    let cnf = std::fs::read_to_string(&cnf_path)
        .map_err(|e| format!("cannot read dumped CNF {}: {e}", cnf_path.display()))?;
    let drat = std::fs::read_to_string(&drat_path)
        .map_err(|e| format!("cannot read DRAT {}: {e}", drat_path.display()))?;

    // 2. Independently re-check with drat-trim BEFORE recording the cert — a
    // cert is only minted once the independent checker confirms.
    //
    // The checker re-reads the artifacts from disk, so re-verify afterwards that
    // the on-disk bytes are still the ones read above. Otherwise a concurrent
    // writer to `workdir` (this fn is `pub`, takes an arbitrary `workdir`, and
    // documents no exclusivity) could have the cert RECORD one CNF while
    // drat-trim CHECKED another — the cert would then carry bytes no checker
    // ever confirmed.
    match drat_trim_check(drat_trim_exe, &cnf_path, &drat_path) {
        DratTrimOutcome::Verified => {}
        other => {
            return Err(format!(
                "drat-trim did not independently confirm the ay proof for {obligation_name:?}: \
                 {other:?}"
            ));
        }
    }
    let cnf_after = std::fs::read_to_string(&cnf_path)
        .map_err(|e| format!("cannot re-read dumped CNF {}: {e}", cnf_path.display()))?;
    let drat_after = std::fs::read_to_string(&drat_path)
        .map_err(|e| format!("cannot re-read DRAT {}: {e}", drat_path.display()))?;
    if cnf_after != cnf || drat_after != drat {
        return Err(format!(
            "workdir artifacts for {obligation_name:?} changed under the independent check \
             (concurrent writer to {}?); refusing to mint a cert over bytes drat-trim did not \
             verify",
            cnf_path.display()
        ));
    }

    let verdict_key = crate::ay_bridge::verdict_cache_key_v2(&solver_identity, smt2);
    Ok(LratCert::new(
        verdict_key,
        solver_identity,
        obligation_name,
        cnf,
        drat,
        smt2,
    ))
}

/// Trim a cert's DRAT proof to its optimized core (`drat-trim -O -l`) and
/// return a new cert carrying the trimmed proof, INDEPENDENTLY re-checked
/// before it is returned. The raw solver-emitted DRAT for a hard obligation
/// can be ~2x the trimmed core (the popcnt width-32 canary: 10.4 MB raw ->
/// ~5 MB core), and the core also re-checks faster — so the trimmed form is
/// what the committed canary certs ship.
///
/// The CNF, `verdict_key`, and `solver_identity` are carried over unchanged
/// (the trim only rewrites the proof half; `LratCert::new` re-derives
/// `cnf_sha256` from the same CNF bytes). Fails — never returns an unchecked
/// cert — if `drat-trim` does not VERIFY the original proof while trimming, or
/// does not independently confirm the trimmed proof afterwards.
pub fn trim_cert(
    cert: &LratCert,
    drat_trim_exe: &Path,
    workdir: &Path,
) -> Result<LratCert, String> {
    let actual = sha256_hex(cert.cnf.as_bytes());
    if actual != cert.cnf_sha256 {
        return Err(format!(
            "cnf integrity mismatch: recorded cnf_sha256={} but recorded CNF hashes to {actual}",
            cert.cnf_sha256
        ));
    }
    std::fs::create_dir_all(workdir)
        .map_err(|e| format!("cannot create workdir {}: {e}", workdir.display()))?;
    let cnf_path = workdir.join("trim.cnf");
    let raw_path = workdir.join("trim.raw.drat");
    let core_path = workdir.join("trim.core.drat");
    std::fs::write(&cnf_path, cert.cnf.as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", cnf_path.display()))?;
    std::fs::write(&raw_path, cert.drat.as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", raw_path.display()))?;

    // Verify + optimize to fixpoint + emit the core lemmas (ASCII DRAT). The
    // trim run itself must VERIFY: drat-trim only emits a meaningful core off
    // a proof it accepted.
    let output = Command::new(drat_trim_exe)
        .arg(&cnf_path)
        .arg(&raw_path)
        .arg("-O")
        .arg("-l")
        .arg(&core_path)
        .output()
        .map_err(|e| format!("spawning drat-trim -O -l failed: {e}"))?;
    if !interpret_drat_trim(&output).is_verified() {
        return Err(format!(
            "drat-trim did not VERIFY the proof for {:?} while trimming",
            cert.obligation_name
        ));
    }
    let core = std::fs::read_to_string(&core_path)
        .map_err(|e| format!("cannot read trimmed core {}: {e}", core_path.display()))?;

    // Independent confirmation of the TRIMMED proof, exactly as a consumer
    // will re-check it.
    match drat_trim_check(drat_trim_exe, &cnf_path, &core_path) {
        DratTrimOutcome::Verified => {}
        other => {
            return Err(format!(
                "drat-trim did not independently confirm the TRIMMED proof for {:?}: {other:?}",
                cert.obligation_name
            ));
        }
    }

    Ok(LratCert::new(
        cert.verdict_key.clone(),
        cert.solver_identity.clone(),
        cert.obligation_name.clone(),
        cert.cnf.clone(),
        core,
        // The trim rewrites only the PROOF half; the obligation binding is
        // carried over unchanged so the trimmed cert still re-derives its key.
        cert.smt2.clone(),
    ))
}

/// Generate a cert for a registry [`ProofObligation`], binding it to the EXACT
/// tier-0 verdict-DB schema: the certified SMT2 is
/// [`crate::verdict_db::db_obligation_smt2`] (what a tier-0 row is keyed by), so
/// the returned cert's `verdict_key` equals that row's key.
pub fn generate_cert_for_obligation(
    obligation: &crate::lowering_proof::ProofObligation,
    ay_exe: &Path,
    drat_trim_exe: &Path,
    workdir: &Path,
) -> Result<LratCert, String> {
    let smt2 = crate::verdict_db::db_obligation_smt2(obligation);
    generate_cert_for_smt2(&obligation.name, &smt2, ay_exe, drat_trim_exe, workdir)
}

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // The export-provenance guard, pinned DIRECTLY.
    //
    // These run with NO solver and are the teeth behind
    // `stale_cnf_cannot_certify_a_simplifier_closed_obligation`, which is an
    // end-to-end test and therefore cannot distinguish "refused for the right
    // reason" from "refused because the guard rejects everything". That
    // distinction is exactly how the previous guard hid a total false negative:
    // it scraped stderr for a `[dump_cnf] Wrote ...` line the current AY never
    // emits, so it refused every obligation, the two end-to-end certification
    // tests failed, and this stale-CNF test passed VACUOUSLY.
    // -----------------------------------------------------------------------

    const PID: u32 = 4242;

    fn hdr(pid: u32) -> String {
        format!("c ay export pid {pid} generation 2\n")
    }

    #[test]
    fn provenance_accepts_this_runs_genuine_bit_blast() {
        let cnf = hdr(PID)
            + "c ay bit-blasted QF_BV CNF (--dump-bv-cnf)\n\
               c complete eager encoding of the current check-sat query\n\
               p cnf 31 80\n1 0\n";
        assert_eq!(
            classify_dumped_cnf(&cnf, PID),
            DumpedCnf::BitBlasted { clauses: 80 }
        );
    }

    #[test]
    fn provenance_refuses_a_simplifier_closed_export() {
        // AY writes this when its SMT rewriter closes the query before the
        // bit-blaster runs. drat-trim reports `c trivial UNSAT` / `s VERIFIED`
        // over it, so accepting it would mint a cert carrying ZERO information
        // about the obligation — the false-cert vector this guard exists for.
        let cnf = hdr(PID) + "c ay canonical false CNF (--dump-bv-cnf)\np cnf 0 1\n0\n";
        assert_eq!(classify_dumped_cnf(&cnf, PID), DumpedCnf::SimplifierClosed);
    }

    #[test]
    fn provenance_refuses_a_canonical_true_export() {
        let cnf = hdr(PID) + "c ay canonical true CNF (--dump-bv-cnf)\np cnf 0 0\n";
        assert_eq!(classify_dumped_cnf(&cnf, PID), DumpedCnf::CanonicalTrue);
    }

    #[test]
    fn provenance_refuses_a_stale_artifact_from_another_process() {
        // A leftover from an earlier obligation: perfectly well-formed, real
        // bit-blast markers, genuinely UNSAT — but NOT written by this run.
        let cnf = hdr(PID + 1) + "c ay bit-blasted QF_BV CNF (--dump-bv-cnf)\np cnf 31 80\n1 0\n";
        assert!(matches!(
            classify_dumped_cnf(&cnf, PID),
            DumpedCnf::ForeignProvenance { .. }
        ));
    }

    #[test]
    fn provenance_refuses_an_unattributed_artifact() {
        let cnf = "p cnf 31 80\n1 0\n";
        assert!(matches!(
            classify_dumped_cnf(cnf, PID),
            DumpedCnf::ForeignProvenance { .. }
        ));
    }

    #[test]
    fn provenance_refuses_an_empty_bit_blast() {
        // 0 clauses: refuting the empty formula is trivially satisfiable.
        let cnf = hdr(PID) + "c ay bit-blasted QF_BV CNF (--dump-bv-cnf)\np cnf 0 0\n";
        assert_eq!(
            classify_dumped_cnf(&cnf, PID),
            DumpedCnf::BitBlasted { clauses: 0 }
        );
    }

    // Golden fixtures: a REAL `ay`-produced bit-blast + DRAT proof of a
    // representative QF_BV lowering-VC-shaped obligation `(bvadd x 1 == x)`,
    // which is UNSAT (no 8-bit x equals x+1). Committed so the independent
    // re-check + tamper teeth run with NO solver present — only the vendored
    // `drat-trim` (dev-dependency) is needed.
    const GOLDEN_SMT2: &str = include_str!("../lrat_fixtures/repr_qfbv.smt2");
    const GOLDEN_CNF: &str = include_str!("../lrat_fixtures/repr_qfbv.cnf");
    const GOLDEN_DRAT: &str = include_str!("../lrat_fixtures/repr_qfbv.drat");

    const DUMMY_KEY: &str = "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";
    const DUMMY_SOLVER: &str = "ffeeddccbbaa99887766554433221100ffeeddccbbaa99887766554433221100";

    fn temp_dir(tag: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "tcg_lrat_cert_{tag}_{}_{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn drat_trim() -> &'static Path {
        trust_cg_drat_trim::drat_trim_executable_path()
    }

    fn golden_cert() -> LratCert {
        // v3: the key must DERIVE from (solver_identity, smt2) or `recheck_cert`
        // rejects the cert on the obligation binding before drat-trim ever runs.
        // Build the fixture consistently so tests exercise the checker, not the
        // binding — the binding has its own dedicated refutation test below.
        LratCert::new(
            crate::ay_bridge::verdict_cache_key_v2(DUMMY_SOLVER, GOLDEN_SMT2),
            DUMMY_SOLVER,
            "repr (bvadd x 1 == x) QF_BV",
            GOLDEN_CNF,
            GOLDEN_DRAT,
            GOLDEN_SMT2,
        )
    }

    /// SCHEMA v3 OBLIGATION BINDING. A cert whose `verdict_key` does not derive
    /// from its own `(solver_identity, smt2)` must be REJECTED — otherwise a cert
    /// is only self-consistent ("this DRAT refutes this CNF") and nothing ties
    /// the named verdict to the obligation text in the same artifact.
    ///
    /// This is the half `drat-trim` stopped covering when generation split into
    /// two AY runs: the DRAT is derived from whatever bytes sit at `cnf_path`, so
    /// drat-trim proves job 2 (this CNF is UNSAT) but no longer incidentally
    /// guards job 1 (this CNF is THIS obligation's bit-blasting).
    #[test]
    fn cert_for_a_different_obligation_is_rejected() {
        let dir = temp_dir("v3_binding");
        // A genuine, fully checkable cert...
        let good = golden_cert();
        assert!(
            recheck_cert(&good, drat_trim(), &dir.join("good")).is_verified(),
            "the consistent fixture must still verify"
        );

        // ...with ONLY the obligation text swapped. The CNF, the DRAT and the
        // key are untouched, so `drat-trim` would still say VERIFIED and the
        // cnf_sha256 integrity check still passes. Only the binding catches it.
        let mut forged = good.clone();
        forged.smt2 = "(set-logic QF_BV)\n(assert false)\n(check-sat)\n".to_string();
        let outcome = recheck_cert(&forged, drat_trim(), &dir.join("forged"));
        assert!(
            !outcome.is_verified(),
            "a cert whose key does not derive from its recorded obligation must NOT verify"
        );
        match outcome {
            DratTrimOutcome::Error(msg) => assert!(
                msg.contains("obligation binding mismatch"),
                "expected the binding diagnostic, got: {msg}"
            ),
            other => panic!("expected an Error verdict, got {other:?}"),
        }

        // Symmetrically: keeping the obligation but forging the KEY must fail.
        let mut wrong_key = good.clone();
        wrong_key.verdict_key = DUMMY_KEY.to_string();
        assert!(
            !recheck_cert(&wrong_key, drat_trim(), &dir.join("wrongkey")).is_verified(),
            "a cert carrying a key its own obligation does not derive must NOT verify"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The independent-checker backstop: the vendored `drat-trim` re-verifies a
    /// REAL ay-produced DRAT proof against its bit-blasted CNF. This is the
    /// machine-checkable half of an ENC-6 verdict, exercised with no ay present.
    #[test]
    fn golden_cert_drat_trim_verifies() {
        let dir = temp_dir("golden_ok");
        let outcome = recheck_cert(&golden_cert(), drat_trim(), &dir);
        assert_eq!(
            outcome,
            DratTrimOutcome::Verified,
            "vendored drat-trim must independently confirm the ay-produced proof"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// TEETH: a withheld proof (no refutation steps at all) is REJECTED —
    /// `drat-trim` reports "no conflict". A cert whose proof body was stripped
    /// must never pass as a Formal verdict.
    ///
    /// (Note: for THIS tiny instance the single lemma `-1 0` is itself a
    /// complete RUP refutation, so merely dropping the trailing empty-clause
    /// line still verifies — which is correct DRAT semantics. Real teeth means
    /// removing the refutation content, done here by emptying the proof.)
    #[test]
    fn withheld_proof_is_rejected() {
        let dir = temp_dir("tamper_proof");
        let mut cert = golden_cert();
        cert.drat = String::new(); // no clauses → no derivation of ⊥
        cert.cnf_sha256 = sha256_hex(cert.cnf.as_bytes()); // keep CNF integrity intact
        let outcome = recheck_cert(&cert, drat_trim(), &dir);
        assert!(
            !outcome.is_verified(),
            "a proof stripped of its refutation must NOT verify, got {outcome:?}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// TEETH: a bogus proof asserting an unrelated clause never derives the
    /// empty clause and is REJECTED.
    #[test]
    fn bogus_proof_is_rejected() {
        let dir = temp_dir("tamper_bogus");
        let mut cert = golden_cert();
        cert.drat = "1 2 0\n".to_string();
        let outcome = recheck_cert(&cert, drat_trim(), &dir);
        assert!(
            !outcome.is_verified(),
            "a proof that does not reach ⊥ must NOT verify, got {outcome:?}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// TEETH: a satisfiable CNF paired with the genuine DRAT is REJECTED
    /// (`drat-trim` reports "conflict claimed, but not detected"). Guards
    /// against a cert whose CNF was swapped for one that is not actually UNSAT.
    #[test]
    fn satisfiable_cnf_is_rejected() {
        let dir = temp_dir("sat_cnf");
        // A trivially-satisfiable formula; rebuild the cert so cnf_sha256 is
        // consistent (else recheck rejects on integrity before drat-trim runs,
        // which would not prove the CHECKER has teeth).
        let cert = LratCert::new(
            crate::ay_bridge::verdict_cache_key_v2(DUMMY_SOLVER, GOLDEN_SMT2),
            DUMMY_SOLVER,
            "satisfiable formula",
            "p cnf 1 1\n1 0\n",
            GOLDEN_DRAT,
            GOLDEN_SMT2,
        );
        let outcome = recheck_cert(&cert, drat_trim(), &dir);
        assert!(
            !outcome.is_verified(),
            "a satisfiable CNF must NOT verify as UNSAT, got {outcome:?}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// TEETH: tampering the recorded CNF bytes is caught by the `cnf_sha256`
    /// integrity binding BEFORE `drat-trim` is even spawned.
    #[test]
    fn cnf_integrity_mismatch_is_rejected() {
        let dir = temp_dir("cnf_integrity");
        let mut cert = golden_cert();
        // Flip a clause literal but keep the (now-stale) recorded hash.
        cert.cnf = cert.cnf.replacen("\n9 0\n", "\n8 0\n", 1);
        assert_ne!(sha256_hex(cert.cnf.as_bytes()), cert.cnf_sha256);
        let outcome = recheck_cert(&cert, drat_trim(), &dir);
        assert!(
            matches!(outcome, DratTrimOutcome::Error(_)),
            "a CNF that does not match its recorded hash must be rejected on integrity, got \
             {outcome:?}"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The recorded-artifact format round-trips, and a header hash edited to
    /// disagree with the payload is rejected by the strict parser.
    #[test]
    fn cert_text_roundtrips_and_rejects_tamper() {
        let cert = golden_cert();
        let text = render_cert(&cert).expect("render");
        let parsed = parse_cert(&text).expect("parse");
        assert_eq!(parsed, cert);

        // A malformed schema line disables parsing.
        assert!(parse_cert(&text.replace(LRAT_CERT_SCHEMA_LINE, "tcg-bogus")).is_err());
        // Editing the cnf-sha256 header so it no longer matches the payload is
        // rejected (the parse-time integrity check).
        let bad = text.replace(&cert.cnf_sha256, DUMMY_KEY);
        assert!(parse_cert(&bad).is_err());
    }

    /// END-TO-END (gated on `ay` being resolvable): generate a fresh cert for
    /// the representative obligation SMT2 via ay's atomic `--dump-bv-cnf` +
    /// `--proof` route, have the vendored drat-trim independently confirm it,
    /// verify the recorded cert re-checks, and verify the `verdict_key` binds
    /// to the verdict-DB schema. Skips cleanly when no ay is present (matches
    /// the solver-optional posture of the rest of the suite).
    #[test]
    fn end_to_end_generate_via_ay() {
        let Some(ay) = crate::ay_bridge::resolved_solver_path() else {
            eprintln!("end_to_end_generate_via_ay: no ay solver resolvable; skipping");
            return;
        };
        let ay = std::path::PathBuf::from(ay);
        let dir = temp_dir("e2e_gen");
        let cert = generate_cert_for_smt2(
            "repr (bvadd x 1 == x) QF_BV",
            GOLDEN_SMT2,
            &ay,
            drat_trim(),
            &dir.join("gen"),
        )
        .expect("cert generation should succeed for an UNSAT QF_BV obligation");

        // Independently re-checkable from the recorded bytes alone.
        assert!(recheck_cert(&cert, drat_trim(), &dir.join("recheck")).is_verified());

        // Round-trips through the recorded-artifact format.
        let text = render_cert(&cert).expect("render fresh cert");
        assert_eq!(parse_cert(&text).expect("parse fresh cert"), cert);

        // Schema binding: the cert backs the byte-identical verdict-DB key.
        let identity = crate::ay_bridge::solver_identity_hash(&ay.to_string_lossy()).unwrap();
        let expected_key = crate::ay_bridge::verdict_cache_key_v2(&identity, GOLDEN_SMT2);
        assert_eq!(cert.verdict_key, expected_key);
        assert_eq!(cert.solver_identity, identity);

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// CONTRACT TEST: every `ay` CLI flag trust-cg actually passes must still be
    /// accepted by the installed solver.
    ///
    /// This exists because `--quiet` was silently removed from `ay solve` and
    /// nothing noticed until two cert tests went red with a confusing
    /// downstream failure. `ay` is NOT a pinned dependency — the solver is
    /// resolved by searching PATH and known build directories — so an unpinned
    /// external prover sits in the trust base and its CLI can drift under us at
    /// any time. This turns that drift into one clear, immediate failure that
    /// names the offending flag.
    ///
    /// It deliberately EXERCISES each flag rather than scraping `--help`:
    /// `--dump-bv-cnf` is functional but undocumented, so a help-text check
    /// would report a false positive for it.
    #[test]
    fn ay_cli_still_accepts_every_flag_trust_cg_passes() {
        let Some(ay) = crate::ay_bridge::resolved_solver_path() else {
            eprintln!("ay_cli_still_accepts_every_flag...: no ay resolvable; skipping");
            return;
        };
        let dir = temp_dir("ay_cli_contract");
        std::fs::create_dir_all(&dir).expect("create workdir");
        let smt2 = dir.join("q.smt2");
        std::fs::write(&smt2, GOLDEN_SMT2).expect("write smt2");

        // (label, args) — each is a real invocation shape from this repo.
        let cnf = dir.join("q.cnf");
        let drat = dir.join("q.drat");
        let alethe = dir.join("q.alethe");
        let invocations: Vec<(&str, Vec<String>)> = vec![
            (
                "lrat_cert step 1a (SMT-LIB bit-blast + CNF dump)",
                vec![
                    "solve".into(),
                    smt2.display().to_string(),
                    "--dump-bv-cnf".into(),
                    cnf.display().to_string(),
                    "--no-verify-proof".into(),
                ],
            ),
            (
                "lrat_cert step 1b (DIMACS refutation + DRAT)",
                vec![
                    "solve".into(),
                    cnf.display().to_string(),
                    "--proof".into(),
                    drat.display().to_string(),
                    "--no-verify-proof".into(),
                ],
            ),
            (
                "alethe proof emission",
                vec![
                    "solve".into(),
                    smt2.display().to_string(),
                    "--proof".into(),
                    alethe.display().to_string(),
                    "--proof-format".into(),
                    "alethe".into(),
                ],
            ),
        ];

        for (label, args) in invocations {
            let out = Command::new(&ay)
                .args(&args)
                .output()
                .unwrap_or_else(|e| panic!("spawning ay for {label} failed: {e}"));
            let stderr = String::from_utf8_lossy(&out.stderr);
            let stdout = String::from_utf8_lossy(&out.stdout);
            // We do NOT assert a verdict here — only that the CLI SURFACE is
            // intact. A drifted/removed flag surfaces as clap's "unexpected
            // argument", and a rejected mode as an "Error:" line.
            assert!(
                !stderr.contains("unexpected argument")
                    && !stderr.contains("unrecognized")
                    && !stdout.contains("unexpected argument"),
                "ay CLI DRIFT — trust-cg passes a flag `ay` no longer accepts.\n\
                 invocation: {label}\n  args: {args:?}\n  stderr: {}",
                stderr.trim()
            );
            assert!(
                !stderr.lines().any(|l| l.trim_start().starts_with("Error:")),
                "ay REJECTED a mode trust-cg depends on.\n\
                 invocation: {label}\n  args: {args:?}\n  stderr: {}",
                stderr.trim()
            );
        }

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A stale CNF left in the workdir by an EARLIER obligation must never be
    /// adopted as this run's output.
    ///
    /// This pins a REAL false-certificate vector, not a hypothetical one. The
    /// dangerous input is a **simplifier-closed** obligation: AY proves it
    /// `unsat` without ever reaching the bit-blaster, so it dumps NO CNF, and
    /// `generate_cert_for_smt2` is supposed to REFUSE to mint (there is no
    /// bit-blasted formula to certify). But the refusal is an `is_file()` check
    /// — so a leftover CNF from a previous obligation satisfies it, the DRAT
    /// step then refutes THAT unrelated formula, `drat-trim` happily verifies
    /// the pair, and the result is a cert whose `verdict_key` names this
    /// obligation while its CNF is a different formula entirely.
    ///
    /// Note the happy path cannot detect this: AY overwrites both artifacts
    /// there, so a stale-artifact test over a normal obligation passes with or
    /// without the fix and proves nothing.
    #[test]
    fn stale_cnf_cannot_certify_a_simplifier_closed_obligation() {
        let Some(ay) = crate::ay_bridge::resolved_solver_path() else {
            eprintln!("stale_cnf_cannot_certify_...: no ay resolvable; skipping");
            return;
        };
        let ay = std::path::PathBuf::from(ay);
        let dir = temp_dir("e2e_stale_simp");
        let workdir = dir.join("gen");
        std::fs::create_dir_all(&workdir).expect("create workdir");

        // `bvadd x y == bvadd x y` is closed by AY's SMT simplifier: it answers
        // unsat at exit 0 and writes no CNF.
        const SIMPLIFIER_CLOSED_SMT2: &str = concat!(
            "(set-logic QF_BV)\n",
            "(declare-const x (_ BitVec 8))\n",
            "(declare-const y (_ BitVec 8))\n",
            "(assert (not (= (bvadd x y) (bvadd x y))))\n",
            "(check-sat)\n"
        );

        // Plant an unrelated but genuinely UNSAT CNF plus a matching DRAT, so
        // every downstream check would succeed on the stale pair.
        let stale_cnf = "p cnf 1 2\n1 0\n-1 0\n";
        std::fs::write(workdir.join("obligation.cnf"), stale_cnf).expect("plant cnf");
        std::fs::write(workdir.join("obligation.drat"), "0\n").expect("plant drat");

        let result = generate_cert_for_smt2(
            "simplifier-closed (bvadd x y == bvadd x y)",
            SIMPLIFIER_CLOSED_SMT2,
            &ay,
            drat_trim(),
            &workdir,
        );

        match result {
            Err(msg) => assert!(
                msg.contains("no DRAT certificate available"),
                "expected the simplifier-closed refusal, got: {msg}"
            ),
            Ok(cert) => panic!(
                "FALSE CERTIFICATE: minted a cert for a simplifier-closed obligation off a \
                 stale CNF ({} bytes); recorded cnf_sha256={}",
                cert.cnf.len(),
                cert.cnf_sha256
            ),
        }

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// END-TO-END (gated on `ay`): certify a GENUINE lowering-VC obligation via
    /// the `ProofObligation` → `db_obligation_smt2` path, and prove the cert's
    /// `verdict_key` equals the tier-0 row key that `verdict_db` would look up
    /// for it — i.e. the cert backs a real Formal verdict, not a toy.
    ///
    /// The VC is the strength-reduction identity `x + x == x << 1` at 8-bit
    /// (double ≡ logical-shift-left-1, the Iadd-double → LSL lowering). Its two
    /// sides are structurally distinct (`bvadd` vs `bvshl`), so ay must actually
    /// BIT-BLAST to refute it — producing the CNF + DRAT that make it
    /// drat-trim-certifiable. (A direct 1:1 lowering like `Iadd -> ADD` is
    /// `add == add`, which ay's simplifier closes WITHOUT bit-blasting, so it
    /// has no DRAT — `generate_cert_for_smt2` correctly returns `Err` for those;
    /// their independent-check lane is the SMT-level Alethe/Lean proof, not
    /// DRAT.)
    #[test]
    fn end_to_end_obligation_binding_via_ay() {
        use crate::smt::SmtExpr;
        let Some(ay) = crate::ay_bridge::resolved_solver_path() else {
            eprintln!("end_to_end_obligation_binding_via_ay: no ay solver resolvable; skipping");
            return;
        };
        let ay = std::path::PathBuf::from(ay);
        let dir = temp_dir("e2e_ob");
        let x = SmtExpr::var("x", 8);
        let ob = crate::lowering_proof::ProofObligation {
            machine_side_provenance: crate::lowering_proof::MachineSideProvenance::StaticDb,
            name: "Idouble_I8 -> LSL#1 (x+x == x<<1)".to_string(),
            trust_ir_expr: x.clone().bvadd(x.clone()),
            aarch64_expr: x.clone().bvshl(SmtExpr::bv_const(1, 8)),
            inputs: vec![("x".to_string(), 8)],
            preconditions: vec![],
            fp_inputs: vec![],
            category: Some(crate::lowering_proof::TransvalCheckKind::InstructionLowering),
        };
        assert!(
            ob.is_genuinely_proven(),
            "the two sides must be structurally distinct (non-degenerate) to force bit-blasting"
        );
        let cert = generate_cert_for_obligation(&ob, &ay, drat_trim(), &dir)
            .expect("x+x == x<<1 is a valid UNSAT lowering VC that bit-blasts and should certify");

        assert!(recheck_cert(&cert, drat_trim(), &dir.join("recheck")).is_verified());

        // The cert's key MUST equal the verdict-DB row key for this obligation.
        let identity = crate::ay_bridge::solver_identity_hash(&ay.to_string_lossy()).unwrap();
        let row_smt2 = crate::verdict_db::db_obligation_smt2(&ob);
        let expected_key = crate::ay_bridge::verdict_cache_key_v2(&identity, &row_smt2);
        assert_eq!(
            cert.verdict_key, expected_key,
            "the LRAT cert must back the exact tier-0 verdict-DB row for this obligation"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// ENC-11 verdict-tier TAXONOMY LOCK (criterion d): an LRAT-certified verdict
    /// — the STRONGEST tier — can only ever be minted from a real `ay` UNSAT plus
    /// an independent drat-trim confirmation. Cert generation takes no
    /// `VerificationStrength`, so there is literally no way to feed a Statistical
    /// (sampled) verdict into it; and with no solver binary present it fails
    /// closed (never mints a cert). This is hermetic (needs no solver): it fails
    /// at the missing-binary step. Teeth: if cert generation ever returned `Ok`
    /// without a real solver proof, this test fails.
    #[test]
    fn enc11_no_lrat_cert_without_a_real_solver_proof() {
        let missing_ay = std::path::Path::new("/nonexistent/enc11-ay-binary");
        let missing_drat = std::path::Path::new("/nonexistent/enc11-drat-trim");
        let dir = temp_dir("enc11_no_solver");
        let res = generate_cert_for_smt2(
            "enc11_probe",
            "(set-logic QF_BV)\n(check-sat)\n",
            missing_ay,
            missing_drat,
            &dir,
        );
        assert!(
            res.is_err(),
            "an LRAT cert must never be minted without a real solver UNSAT proof"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
